Added Navbar and Context API
VishakAmin/bookify pull request #3
Opened 2021-09-03 17:11 UTC by VishakAmin

2021-09-03 17:12 UTC, VishakAmin commented
Also created GraphQL API for adding books.

2021-09-06 05:02 UTC, Stereoraj commented on src/components/Books.js
>      axios.get(`https://www.googleapis.com/books/v1/volumes?q=${searchKey}&key=${process.env.REACT_APP_API_KEY}`)
You can start hooks based api library. 
check this out https://www.npmjs.com/package/swr

2021-09-06 05:04 UTC, Stereoraj commented on src/components/PrivateRoute.js
> -        let fetchUser = async() => {
Use const instead of let wherever possible. This can be used with const wherever possible.

2021-09-06 05:05 UTC, Stereoraj commented on src/components/PrivateRoute.js
>                  let user =  await Auth.currentAuthenticatedUser();
same here. Use const instead of let.

2021-09-06 05:07 UTC, Stereoraj commented on src/components/PrivateRoute.js
>      if(isLoading){
Don't return in multiple places. You are returning at line #29 and #32. This pattern might bring more confusion. What you can instead do is set the result to a variable. And than return that in the same place ( in the end ).

2021-09-06 05:08 UTC, Stereoraj commented on src/components/SignUp.js
> +import { useAuth } from './contexts/AuthContext'
Always separate your internal imports from external space.

`
import { Auth } from 'aws-amplify'
import React,{useState} from 'react'
import { Link, useHistory} from "react-router-dom"

import { useAuth } from './contexts/AuthContext'
`

2021-09-06 05:10 UTC, Stereoraj requested changes
Overall its great. Carry on with this good work. I've left some comments. Most of them are coding standards and best practices concerns. You can follow the same.

2021-09-06 19:07 UTC, merged